name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t quangha2611/my-website .
    - name: Push to Dockerhub
      run: docker push quangha2611/my-website:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull quangha2611/my-website:latest

    - name: Stop old container
      run: sudo docker stop harry_app || true

    - name: Remove old container
      run: sudo docker rm harry_app || true
    
    - name: Run new container
      run: sudo docker run -d --name harry_app -p 80:80 quangha2611/my-website:latest
